export const GET_ERRORS = 'GET_ERRORS';
export const GET_CLASSES = 'GET_CLASSES';
export const GET_EXAMS_CURRENT = 'GET_EXAMS_CURRENT';
export const GET_EXAMS_HISTORY = 'GET_EXAMS_HISTORY';
export const GET_TESTS_ROOT = 'GET_TESTS_ROOT';
export const GET_TESTS_AND_FOLDERS = 'GET_TESTS_AND_FOLDERS';
export const GET_SELECTED_EXAM_CLASSES = 'GET_SELECTED_EXAM_CLASSES';
export const GET_SELECTED_EXAM_TESTS = 'GET_SELECTED_EXAM_TESTS';

export const UPDATE_SELECTED_EXAM_TESTS = 'UPDATE_SELECTED_EXAM_TESTS';

export const GET_CLASSES = "GET_CLASSES";
export const GGET_CLASSES_BY_STUDENT = "GGET_CLASSES_BY_STUDENT";
export const GET_ERRORS = "GET_ERRORS";
export const DELETE_CLASS = "DELETE_CLASS";
export const GET_STUDENTS = "GET_STUDENTS";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const DELETE_STUDENT_TEACHER = "DELETE_STUDENT_TEACHER";
export const GET_GRADE = "GET_GRADE";
export const GET_CLASSSTUDENT = "GET_CLASSSTUDENT";
export const GET_CLASS_STUDENT_BY_STUDENTID = "GET_CLASS_STUDENT_BY_STUDENTID";
export const GET_PARENT = "GET_PARENT";
export const GET_STUDENTTEACHER = "GET_STUDENTTEACHER";
export const GET_CONNECTED_STUDENT = "GET_CONNECTED_STUDENT";
export const GET_CONNECTED_TEACHER = "GET_CONNECTED_TEACHER";
export const GET_STUDENTTEACHER_TEACHER = "GET_STUDENTTEACHER_TEACHER";
export const GET_TEACHER = "GET_TEACHER";
export const GET_EXAM_BY_CLASSID = "GET_EXAM_BY_CLASSID";
export const GET_STUDENT_BY_PARENTID = "GET_STUDENT_BY_PARENTID";
export const PARENT_GET_TEACHER = "PARENT_GET_TEACHER";

