export const GET_ERRORS = 'GET_ERRORS';
export const GET_CLASSES = 'GET_CLASSES';
export const GET_EXAMS_CURRENT = 'GET_EXAMS_CURRENT';
export const GET_EXAMS_HISTORY = 'GET_EXAMS_HISTORY';
export const GET_TESTS_ROOT = 'GET_TESTS_ROOT';
export const GET_TESTS_AND_FOLDERS = 'GET_TESTS_AND_FOLDERS';
export const GET_SELECTED_EXAM_CLASSES = 'GET_SELECTED_EXAM_CLASSES';
export const GET_SELECTED_EXAM_TESTS = 'GET_SELECTED_EXAM_TESTS';

export const UPDATE_SELECTED_EXAM_TESTS = 'UPDATE_SELECTED_EXAM_TESTS';

